package com.android.insecurebankv2;

import android.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

/**
 * Handles AES-256-GCM encryption and decryption
 * 
 * Why GCM (Galois/Counter Mode)?
 * - Provides both confidentiality (encryption) and authenticity (integrity check)
 * - Detects if encrypted data has been tampered with
 * - More secure than CBC mode used in the original implementation
 * 
 * @author Security Team
 */
public class SecureEncryptionManager {

    private static final String CIPHER_ALGORITHM = "AES/GCM/NoPadding";
    private static final int GCM_TAG_LENGTH = 128;  // 128-bit authentication tag
    private static final int GCM_IV_LENGTH = 12;    // 96-bit IV (12 bytes) for GCM

    private KeyStoreManager keyStoreManager;

    public SecureEncryptionManager() {
        this.keyStoreManager = KeyStoreManager.getInstance();
    }

    /**
     * Encrypt a string using AES-256-GCM
     * 
     * Process:
     * 1. Get encryption key from KeyStore
     * 2. Generate random IV (Initialization Vector)
     * 3. Initialize cipher in ENCRYPT mode with the IV
     * 4. Encrypt the plaintext
     * 5. Get authentication tag from cipher
     * 6. Combine IV + ciphertext + tag
     * 7. Base64 encode for storage
     * 
     * @param plaintext String to encrypt (e.g., password)
     * @return Base64-encoded encrypted data (includes IV internally)
     * @throws Exception if encryption fails
     */
    public String encrypt(String plaintext) throws Exception {
        if (plaintext == null || plaintext.isEmpty()) {
            throw new IllegalArgumentException("Plaintext cannot be null or empty");
        }

        try {
            // Get the encryption key from Android KeyStore
            SecretKey key = keyStoreManager.getOrCreateEncryptionKey();

            // Initialize cipher
            Cipher cipher = Cipher.getInstance(CIPHER_ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, key);

            // Get random IV generated by cipher
            byte[] iv = cipher.getIV();
            System.out.println("IV length: " + iv.length + " bytes");

            // Encrypt the plaintext
            byte[] ciphertext = cipher.doFinal(plaintext.getBytes("UTF-8"));

            // Combine IV and ciphertext
            // Format: IV (12 bytes) + Ciphertext + Authentication Tag (included in ciphertext)
            byte[] encryptedData = new byte[iv.length + ciphertext.length];
            System.arraycopy(iv, 0, encryptedData, 0, iv.length);
            System.arraycopy(ciphertext, 0, encryptedData, iv.length, ciphertext.length);

            // Base64 encode for storage in SharedPreferences
            String encodedResult = Base64.encodeToString(encryptedData, Base64.DEFAULT);

            System.out.println("Encryption successful");
            System.out.println("Original length: " + plaintext.length());
            System.out.println("Encrypted length: " + encodedResult.length());

            return encodedResult;

        } catch (Exception e) {
            throw new Exception("Encryption failed: " + e.getMessage(), e);
        }
    }

    /**
     * Decrypt a string using AES-256-GCM
     * 
     * Process:
     * 1. Base64 decode the encrypted data
     * 2. Extract IV from first 12 bytes
     * 3. Extract ciphertext (remainder includes authentication tag)
     * 4. Initialize cipher in DECRYPT mode with the extracted IV
     * 5. Decrypt and verify authentication tag
     * 6. Return plaintext
     * 
     * @param encryptedData Base64-encoded encrypted data
     * @return Decrypted plaintext string
     * @throws Exception if decryption fails or data is tampered with
     */
    public String decrypt(String encryptedData) throws Exception {
        if (encryptedData == null || encryptedData.isEmpty()) {
            throw new IllegalArgumentException("Encrypted data cannot be null or empty");
        }

        try {
            // Base64 decode
            byte[] decodedData = Base64.decode(encryptedData, Base64.DEFAULT);

            // Extract IV (first 12 bytes)
            byte[] iv = new byte[GCM_IV_LENGTH];
            System.arraycopy(decodedData, 0, iv, 0, GCM_IV_LENGTH);

            // Extract ciphertext (everything after IV)
            byte[] ciphertext = new byte[decodedData.length - GCM_IV_LENGTH];
            System.arraycopy(decodedData, GCM_IV_LENGTH, ciphertext, 0, ciphertext.length);

            // Get the decryption key from Android KeyStore
            SecretKey key = keyStoreManager.getOrCreateEncryptionKey();

            // Initialize cipher with IV
            Cipher cipher = Cipher.getInstance(CIPHER_ALGORITHM);
            GCMParameterSpec spec = new GCMParameterSpec(GCM_TAG_LENGTH, iv);
            cipher.init(Cipher.DECRYPT_MODE, key, spec);

            // Decrypt and verify authentication tag
            byte[] plaintext = cipher.doFinal(ciphertext);

            System.out.println("Decryption successful");

            return new String(plaintext, "UTF-8");

        } catch (javax.crypto.AEADBadTagException e) {
            // This exception indicates data tampering
            throw new Exception("Data integrity check failed - data may have been tampered with", e);
        } catch (Exception e) {
            throw new Exception("Decryption failed: " + e.getMessage(), e);
        }
    }
}
